events {}
http {
upstream users_service_upstream { server users_service:8000; }
    server {
        listen 80;
    location /users_service/ {
        proxy_pass http://users_service_upstream/;
    }
    }
}